app:
  port: 18080

db:
  type: mysql
  name: blogs
  host: 127.0.0.1
  port: 3306

jwt:
  secret: cXAhYrcOloCjEGzu
  expiresIn: 7d

secret:
  key: aGVsbG8gdGhlIGFyYyBibG9nLCBiYXNlIG5lc3RqcyBhbmQgb3JtIHByaXNtYS4gbGlrZSBjb2RpbmchCg==
  iv: IGlzIGl2IGhlbGxvIHRoZSBhcmMgYmxvZywgbGlrZSBjb2RpbmchCg==

smtp:
  host: smtp.exmail.qq.com
  port: 456
  user: wangzhenhao@echo9z.wecom.work
  pass: hNAhWrcEXoCjNCzu
  from: wangzhenhao@echo9z.wecom.work

redis:
  log: true
  host: 127.0.0.1
  port: 6379
  password:
  db:
    0 # Defaults to 0
    # key_prefix:

axios:
  timeout: 5000
  maxRedirects: 5

throttle:
  ttl: 60
  limit: 100
